# Generated by Django 5.0.6 on 2024-08-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_spaces', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='parking_images/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
