# Generated by Django 5.0.6 on 2024-05-19 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LicensePlate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_number", models.CharField(max_length=10)),
                ("fecha_entrada", models.DateField(default=datetime.date.today)),
                ("fecha_salida", models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
