# Generated by Django 5.0.6 on 2024-05-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("license_plate", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="licenseplate", old_name="fecha_entrada", new_name="entry_date",
        ),
        migrations.RenameField(
            model_name="licenseplate", old_name="fecha_salida", new_name="exit_date",
        ),
    ]
