# Generated by Django 5.0.6 on 2024-05-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_plate', '0002_rename_fecha_entrada_licenseplate_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseplate',
            name='exit_date',
            field=models.DateField(null=True),
        ),
    ]
