# Generated by Django 5.0.6 on 2024-05-26 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("license_plate", "0003_alter_licenseplate_exit_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenseplate",
            name="entry_time",
            field=models.TimeField(default=datetime.time(12, 20, 12, 934265)),
        ),
        migrations.AddField(
            model_name="licenseplate",
            name="exit_time",
            field=models.TimeField(null=True),
        ),
    ]
