# Generated by Django 5.0.6 on 2024-05-26 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("license_plate", "0004_licenseplate_entry_time_licenseplate_exit_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenseplate",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="licenseplate",
            name="entry_time",
            field=models.TimeField(default=datetime.time(12, 22, 49, 816065)),
        ),
    ]
