# Generated by Django 5.0.6 on 2024-05-29 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_plate', '0005_licenseplate_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseplate',
            name='entry_time',
            field=models.TimeField(default=datetime.time(18, 11, 28, 247737)),
        ),
    ]
