# Generated by Django 5.0.6 on 2024-05-29 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("license_plate", "0006_alter_licenseplate_entry_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenseplate",
            name="entry_time",
            field=models.TimeField(default=datetime.time(18, 12, 36, 900892)),
        ),
    ]
