# Generated by Django 5.0.6 on 2024-05-31 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("license_plate", "0007_alter_licenseplate_entry_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenseplate",
            name="entry_time",
            field=models.TimeField(default=datetime.time(18, 17, 28, 271694)),
        ),
    ]
