# Generated by Django 5.0.6 on 2024-08-19 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_plate', '0008_alter_licenseplate_entry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseplate',
            name='entry_time',
            field=models.TimeField(default=datetime.time(17, 38, 10, 903357)),
        ),
    ]
