# Generated by Django 5.0.6 on 2024-08-19 17:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("license_plate", "0010_alter_licenseplate_entry_time"),
        ("parking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenseplate",
            name="parking",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="parking.parking",
            ),
        ),
        migrations.AlterField(
            model_name="licenseplate",
            name="entry_time",
            field=models.TimeField(default=datetime.time(19, 34, 57, 210656)),
        ),
    ]
