# Generated by Django 5.0.6 on 2024-08-19 17:35

import datetime
import django.db.models.deletion
import license_plate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("license_plate", "0011_licenseplate_parking_alter_licenseplate_entry_time"),
        ("parking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenseplate",
            name="entry_time",
            field=models.TimeField(default=datetime.time(19, 35, 14, 156343)),
        ),
        migrations.AlterField(
            model_name="licenseplate",
            name="parking",
            field=models.ForeignKey(
                default=license_plate.models.get_default_parking,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="parking.parking",
            ),
        ),
    ]
