# Generated by Django 5.0.6 on 2024-08-27 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_plate', '0012_alter_licenseplate_entry_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseplate',
            name='detection_image',
            field=models.ImageField(blank=True, null=True, upload_to='license_plate_images/'),
        ),
        migrations.AlterField(
            model_name='licenseplate',
            name='entry_time',
            field=models.TimeField(default=datetime.time(17, 21, 48, 958822)),
        ),
    ]
