# Generated by Django 5.0.6 on 2024-08-28 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_plate', '0013_licenseplate_detection_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseplate',
            name='entry_time',
            field=models.TimeField(default=datetime.time(2, 8, 16, 285375)),
        ),
    ]
