# Generated by Django 5.1 on 2024-08-29 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_plate', '0014_alter_licenseplate_entry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseplate',
            name='entry_time',
            field=models.TimeField(default=datetime.time(8, 29, 22, 5415)),
        ),
    ]
