# Generated by Django 5.0.6 on 2024-05-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('parking', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Salida')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
