# Generated by Django 5.0.6 on 2024-05-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="direction",
            field=models.CharField(
                choices=[("Entry", "Entrada"), ("Exit", "Salida")], max_length=50
            ),
        ),
    ]
