# Generated by Django 5.0.6 on 2024-05-18 18:23

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(blank=True, max_length=50)),
                ("secondname", models.CharField(blank=True, max_length=50)),
                ("register_date", models.DateField(default=datetime.date.today)),
                ("is_active", models.BooleanField(default=True)),
                ("username", models.CharField(max_length=40, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("is_authenticated", models.BooleanField(default=False)),
                (
                    "code",
                    models.CharField(blank=True, max_length=100, verbose_name="Code"),
                ),
                ("deleted", models.BooleanField(default=False)),
            ],
            options={"db_table": "users",},
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.CreateModel(
            name="LicensePlate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_number", models.CharField(max_length=10)),
                ("fecha_entrada", models.DateField(default=datetime.date.today)),
                ("fecha_salida", models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
