# Generated by Django 5.0.6 on 2024-05-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lpr_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="is_anonymous",),
        migrations.RemoveField(model_name="user", name="is_authenticated",),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default=1234, max_length=40),
            preserve_default=False,
        ),
    ]
