# Generated by Django 5.0.6 on 2024-05-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lpr_app", "0003_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="is_admin", field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user", name="is_staff", field=models.BooleanField(default=True),
        ),
    ]
