# Generated by Django 5.0.6 on 2024-05-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lpr_app", "0005_rename_user_customuser"),
    ]

    operations = [
        migrations.AlterModelTable(name="customuser", table="customuser",),
    ]
