# Generated by Django 5.0.6 on 2024-05-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lpr_app", "0007_rename_customuser_user_alter_user_table"),
    ]

    operations = [
        migrations.DeleteModel(name="LicensePlate",),
    ]
